for c in \
UPLOAD_INITIAL_TIMEOUT_MS \
UPLOAD_MIN_PACKET_TIMEOUT_MS \
UPLOAD_PACKET_TIMEOUT_NORMAL_MS \
UPLOAD_PACKET_TIMEOUT_HIGH_LOSS_MS \
UPLOAD_HIGH_COMPLETION_THRESHOLD \
UPLOAD_LOW_COMPLETION_THRESHOLD \
UPLOAD_PACKET_INTERVAL_MS \
UPLOAD_EXPECTED_RETRIES_PER_SEGMENT \
UPLOAD_GLOBAL_TIMEOUT_MULTIPLIER \
UPLOAD_GLOBAL_TIMEOUT_MAX_MS \
UPLOAD_MAX_RETRIES \
UPLOAD_MAX_SEGMENTS_PER_0X55 \
UPLOAD_INIT_STATE_TIMEOUT_MS \
UPLOAD_ACTIVE_STATE_TIMEOUT_MS \
UPLOAD_TX_SETTLING_MS \
UPLOAD_SAMPLES_PER_SEGMENT \
UPLOAD_BYTES_PER_SAMPLE \
UPLOAD_BYTES_PER_SEGMENT \
UPLOAD_SAMPLES_PER_DESCRIPTOR_UNIT \
BITMAP_SCAN_STRIDE \
BITMAP_OPTIMIZATION_THRESHOLD \
CMD_DELAY_R_TO_R_MS \
CMD_DELAY_R_TO_A_FIRST_MS \
CMD_DELAY_R_TO_A_MS \
CMD_DELAY_A_TO_R_MS \
CMD_DELAY_BETWEEN_NODES_MS \
SESSION_RESPONSE_TIMEOUT_MS \
SESSION_RESPONSE_TIMEOUT_MIN_MS \
SESSION_RESPONSE_TIMEOUT_MAX_MS \
SESSION_DEFAULT_DWELL_COUNT \
RADIO_INIT_RETRY_DELAY_MS \
SESSION_POLL_DELAY_MS; do
  echo "=== $c ==="
  grep -R --color=always -n "$c" --include='*.cpp' --include='*.h' .
  echo
done
